### ISSUE TITLE
Comments in multi-line sigils don't highlight.

### ISSUE THREAD

**Issue by bradgessler** [zed-extensions/ruby#8]
Consider the following block of code:

```ruby
  STATUSES = %w[
    pending             # Pending or awaiting payment
    payment_required    # Payment required
    active              # Active or in good standing
    expired             # Expired or cancelled
    inactive            # Revoked or suspended
  ]
```

In Zed, it renders like this:

<img width="1376" alt="Xnapper-2024-10-28-23 58 16" src="https://github.com/user-attachments/assets/ae9605bf-6a55-4828-9e28-aaadd734a153">

Ideally the comments in the array sigil would be highlighted as a comment so the values are more apparent.

I tested this in other syntax highlighting libraries and they all work like this, but Zed likes going over the top and has TreeSitter, so I figured I'd open a PR on this edge case to see how far it can go.

**Comment by taylorthurlow** [comment]
Unless there's something about your example that is not exactly the problem you're having, this syntax is highlighted correctly. You can't add comments to the array shorthand sigils.

```bash
irb(main):001] STATUSES = %w[
irb(main):002]   pending            # some comment
irb(main):003]   payment_required   # another comment
irb(main):004> ]
=> ["pending", "#", "some", "comment", "payment_required", "#", "another", "comment"]
```

**Comment by bradgessler** [comment]
No you're right, which is funny because I have lots of arrays like this running perfectly fine in production for validations and somehow even tests didn't pick that up.

I guess I have some code to fix.
